#!/bin/bash

if [ $UID -ne 0 ]; then
  echo "error: ${0##*/} must be run as root"
  exit 1
fi

for dev in $(find /sys/class/net/eth*) ; do
  cfg="/etc/network/interfaces.d/${dev##*/}.cfg"
  state=$(cat ${dev}/operstate)
  if [ ! -e "${cfg}" ] && [ "${state}" == "down" ] ; then
    echo 'add' > ${dev}/uevent
  fi
done
